### ISSUE TITLE
Option for YAML to be hidden by default

### ISSUE THREAD

**Issue by ChrisBarfod** [hua03/obsidian-toggle-meta-yaml-plugin#2]
I prefer only showing the YAML metadata when necessary. The rest of the time it's hidden.
Whenever I restart Obsidian I need to toggle this plugin to hide it. Can you give the option to hide the YAML by default?
This would be helpful on mobile too.

**Comment by hua03** [comment]
This is good idea. I will implement it soon.

**Comment by hua03** [comment]
had released, please upgrade to 1.1.0.
